rocprim/CMakeLists.txt
When building with top of 1.8.x branches of HIP and HCC, there is a build issues with missing gridlaunch.h header file. hip::hip_hcc no longer has a dependency on HCC runtime, so we need to use hip::device now. Then we can configure HCC to be the compiler for rocPRIM build using `CXX=/opt/rocm/bin/hcc cmake .. `
=> Fix missing gridlaunch.h build issue

rocprim/include/rocprim/types/tuple.hpp
Remove a semicolon that causes this struct to have no definition.
=> Remove invalid semicolon

rocprim/include/rocprim/device/device_scan_by_key_hip.hpp, rocprim/include/rocprim/device/device_segmented_scan_hip.hpp, rocprim/include/rocprim/iterator/zip_iterator.hpp
HIP-Clang is more strict than HCC. All functions called by device functions must also have __device__ attribute, unlike HCC where device functions can call __host__ only functions.
=> HIP-Clang requires __device__ attr for device func callees

test/rocprim/test_hip_block_exchange.cpp, test/rocprim/test_hip_block_load_store.cpp, test/rocprim/test_hip_transform_iterator.cpp, test/rocprim/test_hip_warp_reduce.cpp, test/rocprim/test_hip_warp_sort.cpp
Remove references to HCC files and vector types, replacing with hip vectors. Add __device__ attribute to functions called by device functions. Replace tile_static with __shared__ attribute.
=> Fix tests to compile with HIP-Clang

hipcub/include/hipcub/rocprim/util_ptx.hpp, rocprim/include/rocprim/warp/detail/warp_segment_bounds.hpp
New intrinsics were added to HIP project, so we can use those instead of hc::.
=> Use HIP-Clang new intrinsics instead of hc::

rocprim/include/rocprim/device/detail/device_reduce_by_key.hpp
This will fix the build errors on HIP-Clang, however, there is still failing 3 of 26 tests in rocprim.device_run_length_encode.
=> Fix build issue with device_run_length_encode

CMakeLists.txt
Since ROCm 1.9 has already VG20 support enabled so we can add gfx906 as target now.
We can delete develop-gfx9 branch as no meaning to keep 2 branch now.
=> add gfx906 as target

install
Copied the install script from rocBLAS to make it easier to run tests via Jenkins.
=> install script for convinience to build and run tests

Jenkinsfile, docker/dockerfile-build-ubuntu-rock, docker/dockerfile-install-ubuntu
For internal continuous integration testing, adding files for Jenkins support.
=> Adding Jenkins support

Jenkinsfile
=> Fixing Jenkinsfile for CI shared library updates

rocprim/include/rocprim/device/device_histogram_config.hpp
Both max_grid_size and shared_impl_max_bins are declared but not defined. This is causing the dependent application to fail to link. 
Eg, tensorflow-rocm uses rocPRIM as a dependency. When doing debug build of tensorflow-rocm using
$ bazel build --config=rocm --copt=-g --copt=-O0  //tensorflow/core/kernels:conv_ops_test --compilation_mode=dbg --strip=never
The build would fail with the below error message:
`bazel-out/k8-dbg/bin/_solib_local/libtensorflow_Score_Skernels_Slibbincount_Uop_Ugpu.so: undefined reference to rocprim::histogram_config<rocprim::kernel_config<256u, 8u>, 1024u, 2048u>::max_grid_size`
@whchung @deven-amd
=> Add definition to max_grid_size and shared_impl_max_bins

rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/device/config_types.hpp, rocprim/include/rocprim/device/detail/device_binary_search.hpp, rocprim/include/rocprim/device/detail/lookback_scan_state.hpp, rocprim/include/rocprim/device/device_merge_sort_config.hpp, rocprim/include/rocprim/device/device_radix_sort_config.hpp
The scan workaround and handle large types with sort.
=> Develop thrust stream

rocprim/include/rocprim/detail/match_result_type.hpp, rocprim/include/rocprim/device/detail/device_transform.hpp, rocprim/include/rocprim/device/device_binary_search.hpp, rocprim/include/rocprim/device/device_scan_by_key.hpp, rocprim/include/rocprim/device/device_segmented_scan.hpp, rocprim/include/rocprim/device/device_transform.hpp, rocprim/include/rocprim/iterator/transform_iterator.hpp
- Implement invoke_result for device-only lambdas
=> Implement invoke_result for device-only lambdas

install
Adding the HIP-Clang path which uses hipcc to compile rocPRIM instead.
=> Add hip-clang install to install script

Jenkinsfile, docker/dockerfile-build-centos, docker/dockerfile-build-ubuntu-rock, docker/dockerfile-install-centos, docker/dockerfile-install-ubuntu, install
=> Added centos and hip-clang support

test/rocprim/test_block_scan.cpp
- To avoid deducing the return type for `__global__` function, which
doesn't understand the deduced return type.
=> Use alternative way for template compile-time switch

rocprim/include/rocprim/block/detail/block_histogram_sort.hpp
New tests revealed intermittent failures in the block histogram function using the sort algorithm on vega10. Looks like a race condition on shared memory that is being reused among many parts of the algorithm. Block histogram (sort) uses rocprim's radix sort function. When radix sort is called with only keys and no values, there is no synchronization after the final write to shared memory in the exchange_keys function. The memory is then reused in the histogram function.
In other words, there is no synchronization between this read from shared memory at the end of :
https://github.com/ROCmSoftwarePlatform/rocPRIM/blob/77494254aaff94751fd816a3fbb038e2ba292060/rocprim/include/rocprim/block/block_radix_sort.hpp#L900
And this write to the same block of shared memory: …
=> Fix race condition on shared memory in histogram with sort algorithm

rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/warp/detail/warp_sort_shuffle.hpp, test/rocprim/test_block_sort.cpp, test/rocprim/test_warp_sort.cpp
Fix bug in block and warp sort for (key, value) pairs that cause values associated with duplicate keys to get lost. Update test code to allow tests with duplicate keys and account for unstable sort algorithms like bitonic.
=> Block and warp sort with duplicate keys

test/rocprim/test_block_radix_sort.cpp, test/rocprim/test_block_sort.cpp, test/rocprim/test_device_binary_search.cpp, test/rocprim/test_device_merge.cpp, test/rocprim/test_device_merge_sort.cpp, test/rocprim/test_device_radix_sort.cpp, test/rocprim/test_device_segmented_radix_sort.cpp, test/rocprim/test_warp_sort.cpp
Supporting hip-clang compiler with C++14. This is a temporary fix and will be removed. Please see https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/100
=> Fix Hip-clang c++14 test compiling

benchmark/benchmark_device_binary_search.cpp, benchmark/benchmark_device_merge.cpp
Workaround C++14 benchmark compilation issue due to `constexpr` automarking with `__host__` and `__device__` in HIP-Clang.
This is related to issue #100 .
=> Fix HIP-Clang C++14 benchmark compiling

benchmark/benchmark_device_binary_search.cpp, benchmark/benchmark_device_merge.cpp, test/rocprim/test_block_radix_sort.cpp, test/rocprim/test_block_sort.cpp, test/rocprim/test_device_binary_search.cpp, test/rocprim/test_device_merge.cpp, test/rocprim/test_device_merge_sort.cpp, test/rocprim/test_device_radix_sort.cpp, test/rocprim/test_device_segmented_radix_sort.cpp, test/rocprim/test_warp_sort.cpp
- That workaround is not required as the bug in clang is fixed.
=> Revert previous workaround for C++14 compilation with HIP-clang.

install
- New mode of building is added "-r,--relocatable" which is used
for ROCm stack installed in /opt/rocm-ver.
- Below CMAKE parameters are set/overwritten in above mode
CMAKE_INSTALL_PREFIX
CMAKE_MODULE_PATH
CMAKE_PREFIX_PATH
Signed-off-by: Pruthvi Madugundu <mpruthvi@gmail.com>
=> rocPRIM changes to support reloctable ROCM installation

rocprim/include/rocprim/device/device_radix_sort.hpp
Include the device_transform.hpp header in device_radix_sort.hpp to fix a compilation issue that occurs when including device_radix_sort alone.
=> Allow including device_radix_sort separately

rocprim/include/rocprim/detail/various.hpp
This reverts commit f1ab775c716973eaff5fbee70fe2c4403d6ab5b6.
This is required to fix Cafe2/PyTorch failures
=> Revert "Add half-overload for load/store-volatile"

rocprim/include/rocprim/detail/various.hpp
Reverts ROCmSoftwarePlatform/rocPRIM#128
Again this is failing testing for Caffe2. Need to incorporate a test case for this into rocPRIM before any new attempt at template specialization.
=> Revert "Avoid template specialization when not using HCC or HIP-CLANG"

.jenkins/precheckin.groovy, docker/dockerfile-build-ubuntu-rock
rocSPARSE CI uses ubuntu 18 so rocPRIM also needs to be built on ubuntu 18
=> Build on rocm-docker ubuntu18

rocprim/include/rocprim/detail/various.hpp
Reverts ROCmSoftwarePlatform/rocPRIM#131
=> Revert "Revert "Avoid template specialization when not using HCC or HIP-CLANG""

rocprim/include/rocprim/block/detail/block_scan_warp_scan.hpp
BlockSize is only declared in the class. It reports missing symbol error when compiled with -O0 and its address is taken or it is passed by reference. Observed while building PyTorch in debug mode.
=> Update calculate_warp_prefixes to initialize BlockSize

.gitlab-ci.yml, test/rocprim/test_seed.hpp, test/rocprim/test_utils.hpp
Increase half tests tolerance. At seed 1997132004, half tests are failing because the error is out of 5%. We had to increase the tolerance value to 7.5% for half type.
=> Increase half tests tolerance

test/rocprim/test_utils_types.hpp, test/rocprim/test_warp_sort.cpp
For gfx1030 warpSize is now 32.  Updating the unit tests so that they build and run properly on gfx1030.
=> Modifying unit test params to not have warpSize > 32 for Navi21/gfx1030

.jenkins/common.groovy
Issue is present on mainline builds 6368 onwards.
=> Disabling device_scan test in jenkins temporarily due to LLVM bug

.gitlab-ci.yml, .gitlab/RunBenchmarks.cmake, rocprim/include/rocprim/config.hpp, rocprim/include/rocprim/device/device_histogram_config.hpp, rocprim/include/rocprim/device/device_merge_config.hpp, rocprim/include/rocprim/device/device_merge_sort_config.hpp, rocprim/include/rocprim/device/device_radix_sort_config.hpp, rocprim/include/rocprim/device/device_reduce_by_key_config.hpp, rocprim/include/rocprim/device/device_reduce_config.hpp, rocprim/include/rocprim/device/device_scan_config.hpp, rocprim/include/rocprim/device/device_segmented_radix_sort_config.hpp, rocprim/include/rocprim/device/device_select_config.hpp, rocprim/include/rocprim/device/device_transform_config.hpp
- Update config parameter and enable ROCPRIM_DETAIL_USE_DPP for gfx90a
- Replace 1031 target with 1030
- Add gitlab ci extend with benchmarks
=> Update config parameter and enable ROCPRIM_DETAIL_USE_DPP for gfx90a

rocprim/include/rocprim/device/device_merge_sort.hpp
- Need to use that temporary stage in the first phase, block_sort, as
the merge sort may be called with the same storage used as both input
and output. Otherwise, it may run into contention and results in
random errors.
=> Fix merge sort.

rocprim/include/rocprim/intrinsics/thread.hpp
This is required to cherry-pick https://github.com/ROCmSoftwarePlatform/rocPRIM/commit/20d2971e6d3ffcbfaca042c1727a15eb31dc5cb2
without having to fast-forward the master branch with all the gfx1030 changes.
=> Adding back deprecated warp_size function temporarily

CMakeLists.txt
include(cmake/Dependencies.cmake) got moved around for the hip-cpu support, causing rocm_check_target_ids to fail.  Manually adding it back in to the appropriate spot when not building for hip-cpu mode so that gfx90a target is built.
=> Fixing cmake dependency include

rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/device/detail/device_merge_sort.hpp, rocprim/include/rocprim/device/device_merge_sort.hpp, rocprim/include/rocprim/device/device_merge_sort_config.hpp, rocprim/include/rocprim/warp/detail/warp_sort_shuffle.hpp, test/rocprim/test_device_merge_sort.cpp
rocm 4.2 mi25 merge sort improvement
```
sort_pairs<int, custom_float2>/manual_time                         749 ms        749 ms          1   5.00862 GB/s   427.402 M items/s
sort_pairs<long long, custom_double2>/manual_time                 1294 ms       1294 ms          1   5.79821 GB/s    247.39 M items/s
sort_pairs<custom_double2, custom_double2>/manual_time            2384 ms       2384 ms          1   4.19383 GB/s   134.202 M items/s
sort_pairs<custom_int2, custom_double2>/manual_time               1091 ms       1091 ms          1   6.87163 GB/s    293.19 M items/s
sort_pairs<custom_int2, custom_char_double>/manual_time           1230 ms       1230 ms          1   6.09692 GB/s   260.135 M items/s
sort_pairs<custom_int2, custom_longlong_double>/manual_time       1092 ms       1092 ms …
```
=> Merge sort improvement at bigger value sizes

CMakeLists.txt
As rocPRIM is a header-only library, use the `HEADER_ONLY` option to `rocm_create_package` in the latest version of `rocm-cmake` to prevent generation of an empty runtime package.
=> Remove runtime package

rmake.py
Removing the top level directory from the zip package so that it is consistent with other math libraries for windows.
=> Removing top level directory from ZIP package

.jenkins/common.groovy
We have 3-6 unit tests failing on gfx90a + HMM.  The number of tests that fail seem to change depending on the machine, and whether or not the entire test suite is being run.  I am currently investigating the failures.  Until a fix is found I think we should disable these as we haven't had a successful artifact in rocPRIM for quite some time, which affects rocThrust and hipCUB CI.
=> Temporarily disabling failing HMM unit tests on CI

rtest.xml
It was previously disabled for PSDB jobs, we also need to disable it for OSDB until we get it fixed.  Already marked as a known issue with rocPRIM.  We need to get a successful build artifact for rocPRIM so that hipCUB develop CI will pass.
=> Disable block histogram test for HIP on Windows OSDB jobs

rocprim/include/rocprim/block/detail/block_histogram_sort.hpp, test/rocprim/test_block_histogram.hpp, test/rocprim/test_block_histogram.kernels.hpp, test/rocprim/test_utils_types.hpp
There is an issue if a single block has all the items, but for now this works.
=> EXSWSTRHPC-129 - Add extra synchronization temporarily to block histogram sort

test/rocprim/test_utils.hpp
The order of evaluation of function parameters in C++ is not guaranteed:
https://stackoverflow.com/questions/2934904/order-of-evaluation-in-c-function-parameters#:~:text=The%20order%20of%20evaluation%20of%20arguments%20is%20unspecified.,will%20be%20called%20before%20foo%20.
With the previous code, the order of evaluation is different on HIP on Windows vs. Linux.  This could lead to *++k_first being evaluated before *k_first, leading to incorrect results.  
I am modifying the code to be unambiguous.  The test now passes on HIP on Windows.
=> Fix ambiguous/undefined order of arguments to function

CHANGELOG.md, rocprim/include/rocprim/block/block_radix_sort.hpp, rocprim/include/rocprim/detail/radix_sort.hpp, rocprim/include/rocprim/device/detail/device_radix_sort.hpp, rocprim/include/rocprim/device/device_radix_sort.hpp, rocprim/include/rocprim/device/device_scan.hpp, rocprim/include/rocprim/device/device_segmented_radix_sort.hpp, rocprim/include/rocprim/types.hpp, rocprim/include/rocprim/types/future_value.hpp, test/rocprim/test_arg_index_iterator.cpp, test/rocprim/test_block_reduce.hpp, test/rocprim/test_block_reduce.kernels.hpp, test/rocprim/test_block_scan.hpp, test/rocprim/test_block_scan.kernels.hpp, test/rocprim/test_device_radix_sort.cpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_device_scan.cpp, test/rocprim/test_device_segmented_reduce.cpp, test/rocprim/test_device_segmented_scan.cpp, test/rocprim/test_device_select.cpp, test/rocprim/test_sort_comparator.hpp, test/rocprim/test_transform_iterator.cpp, test/rocprim/test_utils.hpp, test/rocprim/test_utils_types.hpp, test/rocprim/test_warp_reduce.hpp, test/rocprim/test_warp_scan.hpp, test/rocprim/test_zip_iterator.cpp
* Fix the comperator operator with bigger bit length than 32.
* Also containes future value implementation
* The reduce/scan algorithm precision issues in the tests has been resolved for half types.
=> 309 pytorch unit test failure test tensor creation ops

rtest.xml, test/rocprim/test_utils.hpp
See https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/296 regarding bugfix.
block_histogram, device_scan tests now pass on Windows; device_segmented_radix_sort fails.  Temporarily disabling it on CI so we can get a passing build artifact.
=> Re-enabling/disabling tests for HIP on Windows CI; re-applying bugfix for host scan calculation for unit tests

rocprim/include/rocprim/device/device_scan_by_key.hpp, rocprim/include/rocprim/device/device_scan_by_key_config.hpp
@Snektron:
> Previously, device_scan_by_key used scan_by_key config by default. That failed to take the size of the key into account, leading to problems where too much shared memory would be used if the size of the key was very large.
=> Fixing device_scan_by_key compile error in rocThrust (local memory exceeds limit)

rocprim/CMakeLists.txt
Summary of proposed changes:
- Original Header File Dump enabled for version header file wrapper to support backward Compatibility for PT/TF
- Depends on wrapper functions of rocm-cmake version https://github.com/RadeonOpenCompute/rocm-cmake/commit/d108dbf05e029996d5d7bcbe258abb1166547a30
=> ENABLE ORIGINAL FILE DUMP IN VERSION HDR FILE WRAPPER FOR BKWDCOMP

rocprim/include/rocprim/device/device_scan_by_key.hpp, rocprim/include/rocprim/device/device_scan_by_key_config.hpp
Cherry-pick for ROCm 5.2.  Do not merge until PM approval given.
Previously, device_scan_by_key used scan_by_key config by default. That
failed to take the size of the key into account, leading to problems where
too much shared memory would be used if the size of the key was very large.
Co-authored-by: Robin Voetter <robin@streamhpc.com>
=> Cherry-pick: Add specialized scan by key config (#322)

rocprim/include/rocprim/device/detail/device_radix_sort.hpp
Libraries dependent on rocPRIM may use radix sort and segmented radix
sort with types different from what's known to rocPRIM (e.g. custom
or library wrappers around float16).
This use-case was accidentally broken by using `rocprim::is_floating_point`.
In this case, since the specialization is never actually called at runtime,
the negation of the other condition is more appropriate (i.e. non integers).
In the future clearly defined customization points should be added.
=> Fix radix_merge_sort partial specialization to cover all cases

rocprim/include/rocprim/device/device_segmented_radix_sort.hpp
This fix solves the scenario when the user provided offset operator does not have a `const operator[]`.
=> Mutable lambda in device segmented radix sort

rocprim/include/rocprim/device/detail/device_merge_sort_mergepath.hpp
- Added the missing `ROCPRIM_FORCE_INLINE` directive to the `block_merge_kernel`
- Missing this caused out-of-local-memory errors in debug configuration
- Formatting changes
=> Added force inlining to device_merge_sort_mergepath

rocprim/CMakeLists.txt, toolchain-linux.cmake
Proposed Change:
- Update HIP bin prefix path to ROCM_PATH   (reorg structure)
- enhanced GNUinstall dir (removed additional include, and include install dir mapped to gnuinstalldir.
-
=> Updated HIP Path, enhanced GNU install dir usage

rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/warp/detail/warp_sort_shuffle.hpp
Hotfix due to compiler issue.
Side-effects:
Degrades performance with 5-10% in `warp_sort` & `block_sort` for `float` & `double` datatypes.
Improves performance with 90% in  `warp_sort` for `__half` datatype when `ItemsPerThread==4`.
=> Fix for test failures with rocm 5.3.0 `char`

test/rocprim/test_block_reduce.hpp, test/rocprim/test_block_scan.hpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_device_segmented_reduce.cpp, test/rocprim/test_utils.hpp, test/rocprim/test_warp_reduce.hpp, test/rocprim/test_warp_scan.hpp
Workaround for rocPRIM test failures observed with recent ROCm build. Underlying issue is `double` to `__half` conversion.
=> workaround for double to __half bug causing test failures

rocprim/include/rocprim/device/detail/device_merge_sort_mergepath.hpp
The 20220711 update reverted ROCPRIM_FORCE_INLINE from several device functions.  This is causing pytorch debug builds to fail.  I have confirmed renabling force inline for these two functions fixes the pytorch build issue.
=> Make device_merge_sort_mergepath functions forced inline again

.jenkins/common.groovy
HMM tests are too unstable on CI.  Temporarily disabling until we can figure out whats going on.
=> Disable all HMM tests

CMakeLists.txt, rocprim/CMakeLists.txt
The backwards compatibility headers should not be generated or installed on Windows.
=> HOTFIX: Remove backwards compatibility headers on Windows

rocprim/include/rocprim/config.hpp, rocprim/include/rocprim/device/detail/device_radix_sort.hpp, rocprim/include/rocprim/device/detail/device_scan_by_key.hpp, rocprim/include/rocprim/device/device_histogram_config.hpp, rocprim/include/rocprim/device/device_scan.hpp, scripts/code-format/check-format.sh
I'm preparing the librocprim-dev package for Debian. As part of that process, I ran spellcheck over the repo. It didn't find any particularly meaningful errors, but I figured I'd submit fixes for those that it did catch.
=> Fix spelling and grammar

CHANGELOG.md, rocprim/include/rocprim/detail/merge_path.hpp, test/rocprim/test_device_merge.cpp
Can this fix be backported to ROCm 5.3 ?
=> Develop fix rocm530 device merge iterator mismatch

CMakeLists.txt, benchmark/benchmark_utils.hpp, cmake/Dependencies.cmake, rmake.py
- In MSVC it seems as though int64_t and long long are the same, which leads to multiple definition errors for Traits<> in benchmark_utils
- Explicitly setting the C++ standard to 14 seems to be required in Windows for building the benchmarks, otherwise C++14-related build errors occur
- Enabling benchmark build by default on Windows so any future build errors get caught in CI
=> Fixes to get rocPRIM benchmarks building on Windows

CHANGELOG.md, rocprim/include/rocprim/functional.hpp
Calling printf in device code on Windows can lead to significant performance issues ultimately causing desktop display timeouts.  We currently potentially call printf for the warp operations, specifically for Navi cards if the user tries to use a warp size 64 configuration for the rocPRIM warp operations (Navi by default uses warp size 32).
Until the HIP runtime team fixes the printf performance issues on Windows, we should not use printf.  Adding a compile-time warning was the best solution I can think of, @nolmoonen @vince-streamhpc if there's a better solution you can think of I'm all ears.
=> Temporarily disable printf on Windows

cmake/GenerateResourceSpec.cmake
Currently it only matches numbers in gfx***.  gfx90a is the exception.  Fix will have to be applied to rocthrust and hipcub as well.
=> Correctly match gfx90a in GenerateResourceSpec.cmake

rmake.py, toolchain-windows.cmake
Previously we did not account for spaces in the HIP installation path in Windows (ie. C:\Program Files, etc).
=> HIP SDK compatibility

test/rocprim/test_block_reduce.hpp
For the ReduceMultiplies test case.  Seeing test failures for _half on newer ROCm builds.
=> double to half conversion workaround for test_block_reduce

rocprim/include/rocprim/intrinsics/thread.hpp
This was relying on an implementation detail of the HIP headers which has been removed.
=> Directly use __builtin_amdgcn_fence

rmake.py, toolchain-windows.cmake
Removing unnecessary cmake flags, explicit references to "C:\Program Files\..." which trip up cmake, and old comments.
=> Fix toolchain-windows.cmake for HIP SDK

benchmark/benchmark_utils.hpp
In Windows, the regex in benchmark_utils causes a std::regex_error to be thrown at construction when running any of the benchmarks.  It comes from the right brace.  I'm not entirely sure how the right brace doesn't cause problems in Linux...it is a special regex character.
=> Escape right brace in regex

cmake/Dependencies.cmake, rmake.py
PR #398 broke the ability to find rocm-cmake, and the fallback that was downloaded is too old. This caused the headers to go to `rocprim-runtime[...].zip` instead of `rocprim-devel[...].zip`.
=> Fix package name on Windows

rocprim/include/rocprim/device/detail/device_config_helper.hpp
@stanleytsang-amd Sorry for bugging you again, you will see a small compilation error thrown when building rocThrust, due to the last PR. This fixes that.
=> Fix device_radix_sort for key/value types of 64 bytes

CHANGELOG.md, README.md
Small PR to add a known issue concerning `device_scan` to the changelog for the next release (whether that be 5.5 or 5.6), and update the links to the documentation. This is (provisionally) the last changeset targeting ROCm 5.
=> Fix changelog for 5.5/5.6

docs/device_ops/reduce.rst, rocprim/include/rocprim/device/device_reduce_by_key.hpp
This PR:
- Fixes the reduce by key entry not showing up in docs: [Broken](https://rocm.docs.amd.com/projects/rocPRIM/en/latest/device_ops/reduce.html#id3) vs. [fixed](https://advanced-micro-devices-demo--441.com.readthedocs.build/projects/rocPRIM/en/441/device_ops/reduce.html#id3).
- Documents the (soft) requirement that `reduce_by_key` requires an operator that does not have any side-effects.
=> Fix sphinx error for reduce by key entry

test/rocprim/test_device_radix_sort.hpp
Modify the device_radix_sort test (when requiring more than 4G) to check the memory before running the test. In this case, for Navi32 in the multiVF system it is necessary to keep at least 10% of the total global memory.
=> Navi32 multiVF failing test

test/rocprim/test_device_radix_sort.hpp
This 5.7 cherry pick fixes test device_radix_sort for Navi32 Multi VF.
=> 5.7 cherry pick - fix test device_radix_sort

rocprim/include/rocprim/device/detail/lookback_scan_state.hpp, rocprim/include/rocprim/device/device_partition.hpp, rocprim/include/rocprim/device/device_scan.hpp
We've been advised internally that the gcnArch property in hipDeviceProp_t will be completely removed in ROCm 6.0, as it cannot support full alphanumeric architecture names (ie "gfx90a").
=> Use gcnArchName instead of deprecated gcnArch

benchmark/benchmark_block_sort.parallel.hpp, benchmark/benchmark_device_memory.cpp, benchmark/benchmark_device_radix_sort_onesweep.parallel.hpp, benchmark/benchmark_device_select.cpp, benchmark/benchmark_utils.hpp, benchmark/benchmark_warp_exchange.cpp, benchmark/cmdparser.hpp, test/hip/test_hip_async_copy.cpp, test/rocprim/bounds_checking_iterator.hpp, test/rocprim/identity_iterator.hpp, test/rocprim/test_block_discontinuity.kernels.hpp, test/rocprim/test_block_reduce.kernels.hpp, test/rocprim/test_device_adjacent_difference.cpp, test/rocprim/test_device_partition.cpp, test/rocprim/test_device_scan.cpp, test/rocprim/test_intrinsics.cpp, test/rocprim/test_utils_custom_test_types.hpp, test/rocprim/test_utils_data_generation.hpp, test/rocprim/test_utils_sort_comparator.hpp, test/rocprim/test_warp_exchange.cpp, test/rocprim/test_warp_reduce.hpp, test/rocprim/test_warp_scan.hpp, test/rocprim/test_warp_sort.hpp
Fixed a number of issues that static the analysis tool picked up:
- Made some functions const since they don't modify member state
- Made some parameters const, since they're never modified
- Made some functions static (for performance), since they don't require access to the class instance
- Fixes for several benchmark/test functions:
- Removed unused variable declarations
- Added missing input data transfer from host to device 
- Added default return value for one overlooked execution path 
- Added some member variables to constructor initializer list 
- Added override keyword in several places 
- Fixed up item placeholders in some printf statements
=> Fix cpp-check reported issues

cmake/Dependencies.cmake
The google benchmark version was changed in #434 . However the version it was updated to is broken on Windows, and there doesn't seem to be much attention to the issue, so opening this to revert to the previously used version.
=> Revert googlebenchmark changes

cmake/Dependencies.cmake
See #473 for discussion, updating for ROCm 6.0.
=> Update googlebenchmark version
