ROCmSoftwarePlatform/rocPRIM

rocprim/include/rocprim/block/detail/block_reduce_raking_reduce.hpp
Hi,
Looks good to me. Can we merge to develop?
Saad
=> Remove #pragma unroll from loops with bounds unknown at compile time

NOTICES.txt
NOTICES.txt to comply with legal requirements.
=> Adding NOTICES.txt

rocprim/include/rocprim/device/detail/lookback_scan_state.hpp, rocprim/include/rocprim/device/device_partition.hpp, rocprim/include/rocprim/device/device_scan.hpp
Add sleeps to loops to prevent memory system contention
=> Add sleeps to lookback_scan_state

install
- Can be enabled with -b flag in install script
=> Disable building benchmarks by default

.jenkins/common.groovy
Was creating a deb instead of rpm
=> Fix SLES CI output package

install
=> Fix install script to set cmake build type when using g flag

rocprim/include/rocprim/intrinsics/thread.hpp, test/rocprim/test_block_scan.cpp, test/rocprim/test_utils.hpp
- Containing unmerged PR changes too: #144 
- fix warnings
=> Fix warnings

rocprim/include/rocprim/device/detail/device_reduce_by_key.hpp, test/rocprim/test_arg_index_iterator.cpp, test/rocprim/test_block_reduce.cpp, test/rocprim/test_constant_iterator.cpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_device_scan.cpp, test/rocprim/test_device_segmented_reduce.cpp, test/rocprim/test_device_segmented_scan.cpp, test/rocprim/test_device_transform.cpp, test/rocprim/test_transform_iterator.cpp, test/rocprim/test_warp_reduce.cpp, test/rocprim/test_warp_scan.cpp, test/rocprim/test_warp_sort.cpp, test/rocprim/test_zip_iterator.cpp
At half types we need bigger tolerance value.
=> Fix test precision

.jenkins/common.groovy, .jenkins/precheckin.groovy, docker/dockerfile-build-centos8
=> Replace HCC with HIP-clang

.gitlab-ci.yml, rocprim/include/rocprim/device/device_partition.hpp, rocprim/include/rocprim/device/device_scan.hpp
=> Unused results warning fixed

CMakeLists.txt
=> Adding XNACK flags

README.md
Added link to online documentation in the README
=> Added link to online documentation in the README

rocprim/include/rocprim/intrinsics/warp_shuffle.hpp
Replace move_dpp with update_dpp. It fix test failure in rocThrust.
=> Replace move_dpp with update_dpp

CHANGELOG.md, CMakeLists.txt, test/rocprim/test_utils_types.hpp, test/rocprim/test_warp_sort.cpp
=> Update for ROCm 4.0

.gitlab-ci-gputest.yml, rocprim/include/rocprim/device/device_merge.hpp, rocprim/include/rocprim/device/device_merge_sort.hpp, rocprim/include/rocprim/device/device_radix_sort.hpp, rocprim/include/rocprim/device/device_scan.hpp, rocprim/include/rocprim/device/device_segmented_radix_sort.hpp, rocprim/include/rocprim/device/device_segmented_reduce.hpp, rocprim/include/rocprim/device/device_segmented_scan.hpp, rocprim/include/rocprim/device/device_transform.hpp, test/rocprim/test_device_binary_search.cpp, test/rocprim/test_device_merge.cpp, test/rocprim/test_device_merge_sort.cpp, test/rocprim/test_device_partition.cpp, test/rocprim/test_device_radix_sort.cpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_device_reduce_by_key.cpp, test/rocprim/test_device_run_length_encode.cpp, test/rocprim/test_device_scan.cpp, test/rocprim/test_device_segmented_radix_sort.cpp, test/rocprim/test_device_segmented_reduce.cpp, test/rocprim/test_device_segmented_scan.cpp, test/rocprim/test_device_select.cpp, test/rocprim/test_device_transform.cpp
Handle minimum grid dimension one.
=> Handle minimum grid dimension one

.gitlab-ci.yml, CMakeLists.txt, test/CMakeLists.txt, test/extra/CMakeLists.txt
Update minimum cmake version number
=> Update minimum cmake version number

rocprim/include/rocprim/device/detail/lookback_scan_state.hpp, rocprim/include/rocprim/device/device_scan.hpp
One test of the updated rocThrust build fail, and this change solve the issue.
=> rocThrust update build error fix

benchmark/benchmark_device_merge_sort.cpp, benchmark/benchmark_device_radix_sort.cpp, benchmark/benchmark_warp_sort.cpp, rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/config.hpp, rocprim/include/rocprim/intrinsics/warp_shuffle.hpp, rocprim/include/rocprim/warp/detail/warp_sort_shuffle.hpp
Extend benchmark type2 merge sort and warp sort and performance improvement.
=> Extend benchmark type2 merge sort and warp sort and performance improvement

rocprim/include/rocprim/block/block_reduce.hpp, rocprim/include/rocprim/intrinsics/thread.hpp
Fix warning: https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/223 and update documentation: https://github.com/ROCmSoftwarePlatform/rocPRIM/issues/179
=> Fix warning and update documentation

rocprim/include/rocprim/device/device_radix_sort.hpp, rocprim/include/rocprim/device/device_radix_sort_config.hpp, rocprim/include/rocprim/device/specialization/device_radix_sort.hpp
Update radix sort specialization config
=> Update radix sort specialization config

rocprim/include/rocprim/device/device_merge_sort_config.hpp, rocprim/include/rocprim/device/device_radix_sort_config.hpp
Adjust merge sort launch config parameters
=> Adjust merge sort launch config parameters

rocprim/include/rocprim/block/block_exchange.hpp, rocprim/include/rocprim/intrinsics/thread.hpp
Fix synchronisation in block_exchange functions for Navi cards
=> Add wave_barrier intrinsic

rocprim/include/rocprim/device/detail/device_radix_sort.hpp, rocprim/include/rocprim/device/specialization/device_radix_merge_sort.hpp
Radix merge sort binary operator for pytorch  support. This should fix the build error in pyorch.
=> Radix merge sort binary operator update

CHANGELOG.md, test/rocprim/test_block_histogram.kernels.hpp, test/rocprim/test_block_reduce.kernels.hpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_utils.hpp, test/rocprim/test_utils_types.hpp, test/rocprim/test_warp_reduce.hpp, test/rocprim/test_warp_scan.hpp
=> Enable bfloat16 tests

CHANGELOG.md, README.md, rocprim/include/rocprim/device/detail/device_scan_lookback.hpp
Scan thrust and hipCUB build error fix
=> Scan thrust and hipCUB build error fix

.gitlab-ci.yml, CHANGELOG.md, doc/Doxyfile, rocprim/include/rocprim/block/block_load.hpp, rocprim/include/rocprim/block/block_reduce.hpp, rocprim/include/rocprim/block/block_shuffle.hpp, rocprim/include/rocprim/block/block_store.hpp, rocprim/include/rocprim/iterator/arg_index_iterator.hpp, rocprim/include/rocprim/iterator/constant_iterator.hpp, rocprim/include/rocprim/iterator/counting_iterator.hpp, rocprim/include/rocprim/iterator/discard_iterator.hpp, rocprim/include/rocprim/iterator/texture_cache_iterator.hpp, rocprim/include/rocprim/iterator/transform_iterator.hpp, rocprim/include/rocprim/iterator/zip_iterator.hpp, rocprim/include/rocprim/thread/thread_load.hpp, test/rocprim/test_block_load_store.cpp, test/rocprim/test_block_load_store.kernels.hpp
* Add block_load_striped and block_store_striped
=> Develop stream 20210913

CHANGELOG.md, rocprim/include/rocprim/device/device_scan.hpp, test/rocprim/test_device_merge.cpp, test/rocprim/test_device_merge_sort.cpp, test/rocprim/test_device_radix_sort.cpp, test/rocprim/test_device_reduce.cpp, test/rocprim/test_device_run_length_encode.cpp, test/rocprim/test_device_scan.cpp, test/rocprim/test_device_segmented_radix_sort.cpp, test/rocprim/test_device_select.cpp, test/rocprim/test_utils.hpp
* Fix device scan limit_size feature
* ReduceEmptyInput cause random faulire with bfloat16
=> Fix device scan limit_size feature

CHANGELOG.md, rocprim/include/rocprim/block/block_adjacent_difference.hpp, rocprim/include/rocprim/block/block_discontinuity.hpp, rocprim/include/rocprim/block/block_exchange.hpp, rocprim/include/rocprim/block/block_histogram.hpp, rocprim/include/rocprim/block/block_load.hpp, rocprim/include/rocprim/block/block_radix_sort.hpp, rocprim/include/rocprim/block/block_reduce.hpp, rocprim/include/rocprim/block/block_scan.hpp, rocprim/include/rocprim/block/block_shuffle.hpp, rocprim/include/rocprim/block/block_sort.hpp, rocprim/include/rocprim/block/block_store.hpp, rocprim/include/rocprim/block/detail/block_histogram_sort.hpp, rocprim/include/rocprim/block/detail/block_reduce_raking_reduce.hpp, rocprim/include/rocprim/block/detail/block_reduce_warp_reduce.hpp, rocprim/include/rocprim/block/detail/block_scan_reduce_then_scan.hpp, rocprim/include/rocprim/block/detail/block_scan_warp_scan.hpp, rocprim/include/rocprim/block/detail/block_sort_bitonic.hpp, rocprim/include/rocprim/config.hpp, rocprim/include/rocprim/device/detail/device_merge.hpp, rocprim/include/rocprim/device/detail/device_merge_sort.hpp, rocprim/include/rocprim/device/detail/device_partition.hpp, rocprim/include/rocprim/device/detail/device_radix_sort.hpp, rocprim/include/rocprim/device/detail/device_reduce.hpp, rocprim/include/rocprim/device/detail/device_reduce_by_key.hpp, rocprim/include/rocprim/device/detail/device_scan_lookback.hpp, rocprim/include/rocprim/device/detail/device_scan_reduce_then_scan.hpp, rocprim/include/rocprim/device/detail/device_segmented_radix_sort.hpp, rocprim/include/rocprim/device/detail/device_segmented_reduce.hpp, rocprim/include/rocprim/device/detail/device_segmented_scan.hpp
=> Fix debug shared memory limit

CMakeLists.txt
=> Fix - Corrected Search Path for HIP

.jenkins/common.groovy, rmake.py
Encountering issues on 5.2 RC3.  Temporarily disabling until issues can be fixed.
=> Temporarily disabling warp_reduce test on CI and benchmark build on Windows

rocprim/include/rocprim/detail/various.hpp, rocprim/include/rocprim/device/device_scan_by_key.hpp
When `HIP_TEMPLATE_KERNEL_LAUNCH` is defined `hipLaunchKernelGGL` requires all arguments to match exactly, no implicit conversions allowed.
This change fixes `scan_by_key` removing implicit conversions in the kernel function call, this should fix https://github.com/ROCmSoftwarePlatform/rocThrust/issues/242.
Other algorithms might have similar problems, when the mentioned macro is defined. These must be fixed at a later time, or for better error checking rocPRIM could move away from `hipLaunchKernelGGL` and call `hipLaunchKernel` directly.
=> Fix scan by key for HIP_TEMPLATE_KERNEL_LAUNCH

.jenkins/common.groovy
warp_reduce should work now.  Adding new tests to filter until we can get an handle on if the failures are legitimate.
=> Adjust test filter for CI to get a passing build

benchmark/benchmark_config_dispatch.cpp, scripts/autotune/create_optimization.py, scripts/code-format/check-format.sh, test/rocprim/test_config_dispatch.cpp, test/rocprim/test_utils_custom_float_type.hpp
Not adding to scripts/autotune/fallback_config.json as it is just a markup file with data.  And JSON doesnt seem to have any actual mechanism for comments.
=> Adding copyright notices to new files

rocprim/include/rocprim/device/detail/device_partition.hpp
Previously, a check was performed for the last block of each launch which should have been performed only at the last block across all launches. This gave unintended effects, so the redundant checks are removed. This change has no measurable effects on performance. The bug could be reproduced with sizes `30064767271` and  `17179866528` in the `LargeInputPartition` and `LargeInputPartitionThreeWay` tests.
=> Fix bug in device partition for large problem sizes

CHANGELOG.md, rocprim/include/rocprim/device/detail/device_merge.hpp, test/rocprim/test_device_merge.cpp
https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/381 but targetting `release/rocm-rel-5.3` branch
=> Fix device_merge mismatched input iterators for release/rocm-rel-5.3 branch

rmake.py, rocprim/include/rocprim/functional.hpp, toolchain-windows.cmake
Do not merge until PM approval given
=> 5.4.2 cherry pick fixes

CMakeLists.txt, benchmark/benchmark_utils.hpp, cmake/Dependencies.cmake, rmake.py
Do not merge until PM approval given.
=> 5.4.4 cherry pick

CMakeLists.txt, rocprim/include/rocprim/thread/thread_load.hpp, rocprim/include/rocprim/thread/thread_store.hpp, test/rocprim/test_device_radix_sort.hpp, test/rocprim/test_texture_cache_iterator.cpp
=> Merge back fixes from ROCm 5.7
